<?php

namespace AppBundle\Repository;

/**
 * DenominationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DenominationRepository extends \Doctrine\ORM\EntityRepository
{
}
