<?php

namespace AppBundle\Repository;

/**
 * ResponsabilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponsabilityRepository extends \Doctrine\ORM\EntityRepository
{
}
