<?php
/**
 * Repository for the Responsibility
 */

namespace App\Repository;

/**
 * ResponsibilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponsibilityRepository extends \Doctrine\ORM\EntityRepository
{
}
