<?php
/**
 * Repository for the UserUpdater
 */

namespace App\Repository;

/**
 * UserUpdaterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserUpdaterRepository extends \Doctrine\ORM\EntityRepository
{
}
