#!/bin/bash

# Pre push hook script. Called by "git push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.
# This script start the phpunit test, log the output and allow the push only if the test are successful


#get path to top level directory of the git repertory
dir=`git rev-parse --show-cdup`
#path to the test
phpUnit=$dir'vendor/bin/simple-phpunit'
outputLogTest="/tmp/phpunit_output_`date +%s`.log"

outputLogPHPCS="/tmp/phpcs_output_`date +%s`.log"

phpcs=$dir"vendor/bin/phpcs --colors --report-summary --report-full="$outputLogPHPCS


echo 'Executing tests before pushing...'
echo -e  '---------------------------------- \n'

#print output of test in terminal and in log
$phpUnit| tee $outputLogTest
returnCodeTest=${PIPESTATUS[0]}

echo -e '\n-------------------------------- \n'
echo -e 'Log saved in ' $outputLogTest '\n'

echo -e '\n-------------------------------- \n'
echo -e 'checking code standard... \n'

$phpcs
returnCodePHPCS=$?
echo -e '\n--------------------------------- \n'
echo -e 'Log saved in '$outputLogPHPCS '\n'

if [ $returnCodeTest != 0 ]; then
	echo -e  "PHP unit test failed \n"
fi
if [ $returnCodePHPCS != 0 ]; then
        echo -e  "The code doesn't follow our standard \n"
fi

if [ $returnCodeTest != 0 ]||[ $returnCodePHPCS  != 0 ]; then
	echo -e "Aborting commit \n"
	exit 1
fi

echo -e "committing...\n"
exit 0
